export const actionTypes = {
    ADD_INCOME_TRANSACTION     : 'ADD_INCOME_TRANSACTION',
    ADD_EXPENSE_TRANSACTION    : 'ADD_EXPENSE_TRANSACTION',
    REMOVE_INCOME_TRANSACTION  : 'REMOVE_INCOME_TRANSACTION',
    REMOVE_EXPENSE_TRANSACTION : 'REMOVE_EXPENSE_TRANSACTION'
}